import openai
import time

#unique key for api requests
openai.api_key = 'OpenAI API Key Goes Here'

#api request instructions
def chat_with_gpt(prompt):
    response = openai.Completion.create(
        engine = 'text-davinci-003',
        prompt = prompt,
        max_tokens = 30,
        temperature = 0.5,
        n = 1,
        stop = None
    )

    #index selection of the responses generated by ChatGPT; choosing the first one
    if response.choices:
        return response.choices[0].text.strip()
    else:
        return None

#prompt script
while True:
    text_input = "salt, pepper, oregano, garlic"    #line for detected ingredients
    prompt = f"Please make a recipe from the following list of ingredients: {text_input}\nAI: "

    chapt_gpt_response = chat_with_gpt(prompt)
    print(chapt_gpt_response)

    if chapt_gpt_response is None:
        print("I am sorry I didn't quite catch those ingredients, please try again in 20 seconds.")
    
    rest = 21   #rest statement included to avoid going over open ai request limit
    time.sleep(rest) 

    